### ISSUE TITLE
The default api_key only changes after a server restart

### ISSUE THREAD

**Issue by magopian** [bgaultier/laboitepro#16]
If you look at line https://github.com/bgaultier/laboitepro/blob/774b63846ed372912ad5d37bf4a902eb3cfa0c30/boites/models.py#L19 there's a few issues:
1/ the uuid is only generated once, when the server starts (and the code is loaded)
2/ the field is not [`unique=True`](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.Field.unique) to prevent adding multiple "boites" with the same key
3/ as the default value is generated on each "code load", it changes on each `makemigrations` command, creating a new migration each time for the `boites.models.Boite` model
4/ truncating an `uuid4` might lead to uid clashes, is there a limitation that needs this truncation? (For example, if the uid needs to be entered by hand somewhere?)

**Comment by bgaultier** [comment]
make sense 👍 

I used to to generate this kind of `api_key` manually like so : 
`def make_random_api_key(self):
		allowed_chars = "abcdefghijklmnopqrstuvwxyz0123456789"
		return User.objects.make_random_password(length = 8, allowed_chars = allowed_chars)
`
Good?
I will add `unique=True`, that's for sure !

**Comment by magopian** [comment]
Do you need the length to be only 8? The uuid4 is only guaranteed to have a very low chance of clashing when its full length is used. Truncating it down will greatly increase the chance of having a clash.

I'm working on a patch atm, with the full length of the uuid4 (36 characters). Should I still truncate it down to 8?

**Comment by magopian** [comment]
There's now a PR to fix this issue: https://github.com/bgaultier/laboitepro/pull/17

Warning: it stores the full length of the uuid4. If this is an issue, don't merge it, and let me know, I'll truncate it back to 8.
